# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    mac: 
      operatingSystem: 'macos-latest'  

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- bash: echo ${env.access_key}
- task: CopyFiles@2
  inputs:
    SourceFolder: '/opt/example'
    Contents: '**/**yaml'
    TargetFolder: '/tmp/open'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
